#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.8.101:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      # 全局指定数据库表id自动增长,这样不用到每个entity类中指定@TableId(type=auto)
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#server:
#  port: 10000
#logging:
#  level: debug
